FROM bitnami/tomcat:9.0.41-debian-10-r0
COPY app.war /opt/bitnami/tomcat/webapps_default

# https://artifacthub.io/packages/helm/bitnami/tomcat/7.1.2
# https://hub.docker.com/  (bitnami/tomcat) (.WAR)
